package portfolioboss.db;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * One row of the {@code account_state} table: the account-level figures of the latest snapshot, one row
 * per account, replaced on every sync. A figure IB did not report is {@code null}.
 */
@Entity
@Table(name = "account_state")
public class AccountStateEntity {

    /** The IB account id. Assigned by us, not generated by the database. */
    @Id
    private String account;

    private Instant asOf;
    private Double netLiquidation;
    private Double totalCashValue;

    /** Required by JPA, which creates entities by reflection. */
    protected AccountStateEntity() {
    }
}
